server:
  port: 8081
  max-http-header-size: 8KB

  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_proxy?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

jjwt:
  secret: 

wikihost:
  x_api_key:
  x_api_password:
